type EnvName =
  // Auth
  | "CLERK_SECRET_KEY"
  | "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY"
  // Supabase
  | "NEXT_PUBLIC_SUPABASE_URL"
  | "NEXT_PUBLIC_SUPABASE_ANON_KEY"
  | "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY"
  | "SUPABASE_SERVICE_ROLE_KEY"
  // Stripe
  | "STRIPE_SECRET_KEY"
  | "STRIPE_WEBHOOK_SECRET"
  | "STRIPE_PRICE_ID"
  | "STRIPE_PRICE_ID_SETUP"
  | "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY"
  | "STRIPE_CLIENT_ID"
  | "STRIPE_CLIENT_SECRET"
  // AI
  | "GEMINI_API_KEY"
  | "GOOGLE_GENERATIVE_AI_API_KEY"
  // Messaging
  | "RESEND_API_KEY"
  | "RESEND_FROM_EMAIL"
  | "TWILIO_ACCOUNT_SID"
  | "TWILIO_AUTH_TOKEN"
  | "TWILIO_PHONE_NUMBER"
  | "MAILGUN_API_KEY"
  | "MAILGUN_DOMAIN"
  | "MAILGUN_FROM_EMAIL"
  | "MAILGUN_WEBHOOK_SIGNING_KEY"
  // Redis / queues
  | "REDIS_URL"
  | "UPSTASH_REDIS_REST_URL"
  | "UPSTASH_REDIS_REST_TOKEN"
  // Integrations
  | "QUICKBOOKS_CLIENT_ID"
  | "QUICKBOOKS_CLIENT_SECRET"
  | "QUICKBOOKS_WEBHOOK_VERIFIER_TOKEN"
  | "HUBSPOT_CLIENT_ID"
  | "HUBSPOT_CLIENT_SECRET"
  | "JOBBER_CLIENT_ID"
  | "JOBBER_CLIENT_SECRET"
  | "SQUARE_CLIENT_ID"
  | "SQUARE_CLIENT_SECRET"
  | "GOOGLE_CLIENT_ID"
  | "GOOGLE_CLIENT_SECRET"
  | "NEXT_PUBLIC_GOOGLE_API_KEY"
  | "NEXT_PUBLIC_GOOGLE_PICKER_APP_ID"
  // App
  | "NEXT_PUBLIC_APP_URL"
  | "CRON_SECRET"
  | "LEAD_INGEST_SECRET"
  | "ADMIN_EMAILS";

export function getEnv(name: EnvName) {
  const value = process.env[name];

  if (!value) {
    throw new Error(`Missing required environment variable: ${name}`);
  }

  return value;
}

export function getSupabaseAnonKey() {
  return (
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ??
    process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY ??
    ""
  );
}
