export type BusinessSector =
  | "general"
  | "medical" | "dental" | "physical_therapy" | "mental_health" | "chiropractic" | "veterinary"
  | "construction" | "electrical" | "plumbing" | "hvac" | "roofing" | "general_contractor"
  | "home_services" | "landscaping" | "cleaning" | "pest_control" | "painting"
  | "professional_services" | "legal" | "accounting" | "consulting" | "agency" | "it_services" | "financial_advisory"
  | "fitness" | "photography" | "beauty" | "auto_repair"
  | "insurance" | "real_estate" | "tattoo" | "auto_detailing";

export type IndustryProfile = {
  id: BusinessSector;
  label: string;
  headline: string;
  dailyFocus: string;
  labels: {
    customerSingular: string;
    customerPlural: string;
    leadSingular: string;
    leadPlural: string;
    jobSingular: string;
    jobPlural: string;
    saleSingular: string;
    salePlural: string;
    followUpSingular: string;
    followUpPlural: string;
  };
  priorityNames: {
    pipeline: string;
    activeWork: string;
    revenue: string;
    followUps: string;
    dataHealth: string;
  };
  insightPrompts: string[];
  pipelineLabel: string;
  recordLabel: string;
  recordPlural: string;
  completedLabel: string;
  cancelledLabel: string;
  valueLabel: string;
  invoiceLabel: string;
  targetDateLabel: string;
  activeStatusLabel: string;
  inactiveStatusLabel: string;
  closedStatusLabel: string;
  sourceOptions: string[];
  defaultBoardName: string;
  defaultStages: Array<{
    name: string;
    stageType: "active" | "completed" | "cancelled" | "on_hold";
    position: number;
    color: string;
  }>;
  defaultTags: string[];
  agentProfile: {
    focusArea: string;
    keyMetrics: string[];
    avoidLanguage: string[];
  };
};

export const industryProfiles: Record<BusinessSector, IndustryProfile> = {
  general: {
    id: "general",
    label: "General Business",
    headline: "Business overview",
    dailyFocus:
      "Track contacts, opportunities, work, sales, and follow-ups from one workspace.",
    labels: {
      customerSingular: "Contact",
      customerPlural: "Contacts",
      leadSingular: "Opportunity",
      leadPlural: "Opportunities",
      jobSingular: "Task",
      jobPlural: "Tasks",
      saleSingular: "Sale",
      salePlural: "Sales",
      followUpSingular: "Follow-up",
      followUpPlural: "Follow-ups",
    },
    priorityNames: {
      pipeline: "Pipeline value",
      activeWork: "Active tasks",
      revenue: "Revenue",
      followUps: "Follow-ups due",
      dataHealth: "Data quality",
    },
    insightPrompts: [
      "Which contacts or opportunities haven't had any activity this week?",
      "Which sales are unpaid or past due?",
      "Which records are missing key details before they're useful?",
    ],
    pipelineLabel: "Pipeline",
    recordLabel: "Record",
    recordPlural: "Records",
    completedLabel: "Completed",
    cancelledLabel: "Cancelled",
    valueLabel: "Value",
    invoiceLabel: "Invoice",
    targetDateLabel: "Due Date",
    activeStatusLabel: "Active",
    inactiveStatusLabel: "Inactive",
    closedStatusLabel: "Closed",
    sourceOptions: ["Referral", "Website", "Social Media", "Cold Outreach", "Event", "Other"],
    defaultBoardName: "Pipeline",
    defaultStages: [
      { name: "New", stageType: "active", position: 0, color: "#6366f1" },
      { name: "In Progress", stageType: "active", position: 1, color: "#3b82f6" },
      { name: "Completed", stageType: "completed", position: 2, color: "#22c55e" },
      { name: "Cancelled", stageType: "cancelled", position: 3, color: "#ef4444" },
    ],
    defaultTags: ["High Priority", "Follow-up", "VIP", "New"],
    agentProfile: {
      focusArea: "overall business health, pipeline, and follow-up activity",
      keyMetrics: ["open opportunities", "revenue", "follow-ups due", "data completeness"],
      avoidLanguage: [],
    },
  },

  medical: {
    id: "medical",
    label: "Medical / Healthcare",
    headline: "Practice operations view",
    dailyFocus:
      "Track patients, unscheduled treatment, appointments, collections, and care tasks for medical practices.",
    labels: {
      customerSingular: "Patient",
      customerPlural: "Patients",
      leadSingular: "Treatment case",
      leadPlural: "Treatment cases",
      jobSingular: "Appointment",
      jobPlural: "Appointments",
      saleSingular: "Collection",
      salePlural: "Collections",
      followUpSingular: "Care task",
      followUpPlural: "Care tasks",
    },
    priorityNames: {
      pipeline: "Unscheduled treatment value",
      activeWork: "Scheduled appointments",
      revenue: "Collections",
      followUps: "Care tasks due",
      dataHealth: "Chart completeness",
    },
    insightPrompts: [
      "Which patients have unscheduled treatment or are past due for recall?",
      "Which treatment cases haven't been scheduled yet?",
      "Which charts are missing contact details or case notes?",
    ],
    pipelineLabel: "Patient Journey",
    recordLabel: "Case",
    recordPlural: "Cases",
    completedLabel: "Resolved",
    cancelledLabel: "Withdrawn",
    valueLabel: "Treatment Value",
    invoiceLabel: "Statement",
    targetDateLabel: "Expected Date",
    activeStatusLabel: "Active",
    inactiveStatusLabel: "Inactive",
    closedStatusLabel: "Discharged",
    sourceOptions: ["Referral", "Website", "Insurance Network", "Walk-in", "Social Media"],
    defaultBoardName: "Patient Journey",
    defaultStages: [
      { name: "Needs Scheduling", stageType: "active", position: 0, color: "#6366f1" },
      { name: "Scheduled", stageType: "active", position: 1, color: "#3b82f6" },
      { name: "In Treatment", stageType: "active", position: 2, color: "#f59e0b" },
      { name: "Resolved", stageType: "completed", position: 3, color: "#22c55e" },
      { name: "Withdrawn", stageType: "cancelled", position: 4, color: "#ef4444" },
    ],
    defaultTags: ["New Patient", "High Value", "Recall Due", "Insurance", "Payment Plan"],
    agentProfile: {
      focusArea: "patient care continuity, unscheduled treatment, and collections",
      keyMetrics: ["unscheduled treatment value", "scheduled appointments", "collections", "recall due"],
      avoidLanguage: ["win rate", "close date", "deal", "prospect"],
    },
  },

  dental: {
    id: "dental",
    label: "Dental Practice",
    headline: "Dental practice operations view",
    dailyFocus:
      "Track patients, treatment cases, appointments, collections, and recall for dental practices.",
    labels: {
      customerSingular: "Patient",
      customerPlural: "Patients",
      leadSingular: "Treatment case",
      leadPlural: "Treatment cases",
      jobSingular: "Appointment",
      jobPlural: "Appointments",
      saleSingular: "Collection",
      salePlural: "Collections",
      followUpSingular: "Care task",
      followUpPlural: "Care tasks",
    },
    priorityNames: {
      pipeline: "Unscheduled treatment value",
      activeWork: "Scheduled appointments",
      revenue: "Collections",
      followUps: "Care tasks due",
      dataHealth: "Chart completeness",
    },
    insightPrompts: [
      "Which patients have unscheduled treatment or are overdue for recall?",
      "Which treatment cases haven't been scheduled yet?",
      "Which patients are missing insurance information or contact details?",
    ],
    pipelineLabel: "Patient Journey",
    recordLabel: "Treatment Case",
    recordPlural: "Treatment Cases",
    completedLabel: "Treatment Complete",
    cancelledLabel: "Withdrawn",
    valueLabel: "Treatment Value",
    invoiceLabel: "Statement",
    targetDateLabel: "Expected Date",
    activeStatusLabel: "Active",
    inactiveStatusLabel: "Inactive",
    closedStatusLabel: "Discharged",
    sourceOptions: ["Referral", "Website", "Insurance Network", "Walk-in", "Social Media"],
    defaultBoardName: "Patient Journey",
    defaultStages: [
      { name: "Exam Needed", stageType: "active", position: 0, color: "#6366f1" },
      { name: "Treatment Planned", stageType: "active", position: 1, color: "#3b82f6" },
      { name: "In Treatment", stageType: "active", position: 2, color: "#f59e0b" },
      { name: "Treatment Complete", stageType: "completed", position: 3, color: "#22c55e" },
      { name: "Withdrawn", stageType: "cancelled", position: 4, color: "#ef4444" },
    ],
    defaultTags: ["New Patient", "High Value", "Recall Due", "Insurance", "Payment Plan"],
    agentProfile: {
      focusArea: "unscheduled treatment, recall, and collection performance",
      keyMetrics: ["unscheduled treatment value", "recall rate", "collections", "case acceptance"],
      avoidLanguage: ["win rate", "close date", "deal", "prospect", "customer"],
    },
  },

  physical_therapy: {
    id: "physical_therapy",
    label: "Physical Therapy",
    headline: "PT practice operations view",
    dailyFocus:
      "Track patients, episodes of care, sessions, authorizations, and discharge planning.",
    labels: {
      customerSingular: "Patient",
      customerPlural: "Patients",
      leadSingular: "Episode of care",
      leadPlural: "Episodes of care",
      jobSingular: "Session",
      jobPlural: "Sessions",
      saleSingular: "Collection",
      salePlural: "Collections",
      followUpSingular: "Care task",
      followUpPlural: "Care tasks",
    },
    priorityNames: {
      pipeline: "Auth value",
      activeWork: "Active sessions",
      revenue: "Collections",
      followUps: "Care tasks due",
      dataHealth: "Chart completeness",
    },
    insightPrompts: [
      "Which patients are approaching their authorization limit?",
      "Which episodes of care are missing discharge goals?",
      "Which patients haven't had a session in the past two weeks?",
    ],
    pipelineLabel: "Patient Journey",
    recordLabel: "Episode of Care",
    recordPlural: "Episodes of Care",
    completedLabel: "Discharged",
    cancelledLabel: "Discontinued",
    valueLabel: "Auth Value",
    invoiceLabel: "Statement",
    targetDateLabel: "Expected Discharge Date",
    activeStatusLabel: "Active",
    inactiveStatusLabel: "Inactive",
    closedStatusLabel: "Discharged",
    sourceOptions: ["Physician Referral", "Insurance Network", "Self-Referral", "Hospital", "Website"],
    defaultBoardName: "Patient Journey",
    defaultStages: [
      { name: "Intake", stageType: "active", position: 0, color: "#6366f1" },
      { name: "Evaluation", stageType: "active", position: 1, color: "#3b82f6" },
      { name: "Active Treatment", stageType: "active", position: 2, color: "#f59e0b" },
      { name: "Discharged", stageType: "completed", position: 3, color: "#22c55e" },
      { name: "Discontinued", stageType: "cancelled", position: 4, color: "#ef4444" },
    ],
    defaultTags: ["New Patient", "Auth Expiring", "High Complexity", "Insurance", "Home Program"],
    agentProfile: {
      focusArea: "authorization utilization, care progression, and discharge planning",
      keyMetrics: ["active episodes", "visits authorized vs used", "collections", "discharge rate"],
      avoidLanguage: ["win rate", "close date", "deal", "prospect", "customer", "sale"],
    },
  },

  mental_health: {
    id: "mental_health",
    label: "Mental Health Practice",
    headline: "Mental health practice operations view",
    dailyFocus:
      "Track clients, treatment episodes, sessions, and care continuity for mental health practices.",
    labels: {
      customerSingular: "Client",
      customerPlural: "Clients",
      leadSingular: "Treatment episode",
      leadPlural: "Treatment episodes",
      jobSingular: "Session",
      jobPlural: "Sessions",
      saleSingular: "Collection",
      salePlural: "Collections",
      followUpSingular: "Care task",
      followUpPlural: "Care tasks",
    },
    priorityNames: {
      pipeline: "Active caseload value",
      activeWork: "Scheduled sessions",
      revenue: "Collections",
      followUps: "Care tasks due",
      dataHealth: "Record completeness",
    },
    insightPrompts: [
      "Which clients haven't had a session in the past two weeks?",
      "Which treatment episodes are missing treatment goals?",
      "Which clients are missing insurance or billing information?",
    ],
    pipelineLabel: "Client Journey",
    recordLabel: "Treatment Episode",
    recordPlural: "Treatment Episodes",
    completedLabel: "Completed",
    cancelledLabel: "Discontinued",
    valueLabel: "Session Value",
    invoiceLabel: "Statement",
    targetDateLabel: "Expected Completion",
    activeStatusLabel: "Active",
    inactiveStatusLabel: "Inactive",
    closedStatusLabel: "Closed",
    sourceOptions: ["Referral", "Insurance Network", "Self-Referral", "Website", "Employee Assistance Program"],
    defaultBoardName: "Client Journey",
    defaultStages: [
      { name: "Intake", stageType: "active", position: 0, color: "#6366f1" },
      { name: "Assessment", stageType: "active", position: 1, color: "#3b82f6" },
      { name: "Active Treatment", stageType: "active", position: 2, color: "#f59e0b" },
      { name: "Completed", stageType: "completed", position: 3, color: "#22c55e" },
      { name: "Discontinued", stageType: "cancelled", position: 4, color: "#ef4444" },
    ],
    defaultTags: ["New Client", "High Risk", "Insurance", "Sliding Scale", "Waitlist"],
    agentProfile: {
      focusArea: "client engagement, care continuity, and caseload management",
      keyMetrics: ["active caseload", "session attendance", "collections", "no-show rate"],
      avoidLanguage: ["win rate", "close date", "deal", "prospect", "customer", "sale", "revenue"],
    },
  },

  chiropractic: {
    id: "chiropractic",
    label: "Chiropractic Practice",
    headline: "Chiropractic practice operations view",
    dailyFocus:
      "Track patients, treatment cases, visits, collections, and care continuity.",
    labels: {
      customerSingular: "Patient",
      customerPlural: "Patients",
      leadSingular: "Treatment case",
      leadPlural: "Treatment cases",
      jobSingular: "Visit",
      jobPlural: "Visits",
      saleSingular: "Collection",
      salePlural: "Collections",
      followUpSingular: "Care task",
      followUpPlural: "Care tasks",
    },
    priorityNames: {
      pipeline: "Unscheduled treatment value",
      activeWork: "Scheduled visits",
      revenue: "Collections",
      followUps: "Care tasks due",
      dataHealth: "Chart completeness",
    },
    insightPrompts: [
      "Which patients haven't been in for a visit in the past month?",
      "Which treatment cases haven't been scheduled?",
      "Which patients are missing insurance details or case notes?",
    ],
    pipelineLabel: "Patient Journey",
    recordLabel: "Treatment Case",
    recordPlural: "Treatment Cases",
    completedLabel: "Treatment Complete",
    cancelledLabel: "Withdrawn",
    valueLabel: "Treatment Value",
    invoiceLabel: "Statement",
    targetDateLabel: "Expected Date",
    activeStatusLabel: "Active",
    inactiveStatusLabel: "Inactive",
    closedStatusLabel: "Discharged",
    sourceOptions: ["Referral", "Website", "Insurance Network", "Walk-in", "Social Media"],
    defaultBoardName: "Patient Journey",
    defaultStages: [
      { name: "New Patient", stageType: "active", position: 0, color: "#6366f1" },
      { name: "Treatment Planned", stageType: "active", position: 1, color: "#3b82f6" },
      { name: "Active Care", stageType: "active", position: 2, color: "#f59e0b" },
      { name: "Maintenance", stageType: "active", position: 3, color: "#8b5cf6" },
      { name: "Treatment Complete", stageType: "completed", position: 4, color: "#22c55e" },
      { name: "Withdrawn", stageType: "cancelled", position: 5, color: "#ef4444" },
    ],
    defaultTags: ["New Patient", "High Value", "Recall Due", "Insurance", "Cash Patient"],
    agentProfile: {
      focusArea: "patient retention, unscheduled treatment, and visit frequency",
      keyMetrics: ["active cases", "visit frequency", "collections", "patient retention"],
      avoidLanguage: ["win rate", "close date", "deal", "prospect", "customer"],
    },
  },

  veterinary: {
    id: "veterinary",
    label: "Veterinary Practice",
    headline: "Veterinary practice operations view",
    dailyFocus:
      "Track patients (pets), appointments, cases, collections, and follow-up care.",
    labels: {
      customerSingular: "Pet Owner",
      customerPlural: "Pet Owners",
      leadSingular: "Case",
      leadPlural: "Cases",
      jobSingular: "Appointment",
      jobPlural: "Appointments",
      saleSingular: "Collection",
      salePlural: "Collections",
      followUpSingular: "Care task",
      followUpPlural: "Care tasks",
    },
    priorityNames: {
      pipeline: "Open case value",
      activeWork: "Scheduled appointments",
      revenue: "Collections",
      followUps: "Care tasks due",
      dataHealth: "Record completeness",
    },
    insightPrompts: [
      "Which patients are overdue for wellness visits or vaccinations?",
      "Which cases are missing treatment details or follow-up plans?",
      "Which owners haven't been in contact for over three months?",
    ],
    pipelineLabel: "Patient Journey",
    recordLabel: "Case",
    recordPlural: "Cases",
    completedLabel: "Resolved",
    cancelledLabel: "Withdrawn",
    valueLabel: "Treatment Value",
    invoiceLabel: "Invoice",
    targetDateLabel: "Expected Date",
    activeStatusLabel: "Active",
    inactiveStatusLabel: "Inactive",
    closedStatusLabel: "Discharged",
    sourceOptions: ["Referral", "Website", "Walk-in", "Social Media", "Emergency"],
    defaultBoardName: "Patient Journey",
    defaultStages: [
      { name: "Intake", stageType: "active", position: 0, color: "#6366f1" },
      { name: "Diagnosis", stageType: "active", position: 1, color: "#3b82f6" },
      { name: "Treatment", stageType: "active", position: 2, color: "#f59e0b" },
      { name: "Resolved", stageType: "completed", position: 3, color: "#22c55e" },
      { name: "Withdrawn", stageType: "cancelled", position: 4, color: "#ef4444" },
    ],
    defaultTags: ["New Patient", "High Value", "Recall Due", "Wellness Due", "Chronic Condition"],
    agentProfile: {
      focusArea: "patient wellness compliance, recall scheduling, and collections",
      keyMetrics: ["active cases", "wellness compliance", "collections", "appointment adherence"],
      avoidLanguage: ["win rate", "close date", "deal", "prospect"],
    },
  },

  construction: {
    id: "construction",
    label: "Construction / Contractor",
    headline: "Job and estimate view",
    dailyFocus:
      "Track customers, estimates, active jobs, invoices, and follow-ups for contractors, builders, and tradespeople.",
    labels: {
      customerSingular: "Customer",
      customerPlural: "Customers",
      leadSingular: "Estimate",
      leadPlural: "Estimates",
      jobSingular: "Job",
      jobPlural: "Jobs",
      saleSingular: "Invoice",
      salePlural: "Invoices",
      followUpSingular: "Job task",
      followUpPlural: "Job tasks",
    },
    priorityNames: {
      pipeline: "Open estimate value",
      activeWork: "Active jobs",
      revenue: "Job revenue",
      followUps: "Job tasks due",
      dataHealth: "Job data quality",
    },
    insightPrompts: [
      "Which estimates haven't had a response in over a week?",
      "Which jobs have unpaid or partial invoices outstanding?",
      "Which jobs are missing a value, start date, or customer?",
    ],
    pipelineLabel: "Project Board",
    recordLabel: "Project",
    recordPlural: "Projects",
    completedLabel: "Completed",
    cancelledLabel: "Cancelled",
    valueLabel: "Contract Value",
    invoiceLabel: "Invoice",
    targetDateLabel: "Target Date",
    activeStatusLabel: "Active",
    inactiveStatusLabel: "Inactive",
    closedStatusLabel: "Closed",
    sourceOptions: ["Referral", "Website", "Door-to-Door", "Lead Service", "Repeat Customer", "Other"],
    defaultBoardName: "Project Board",
    defaultStages: [
      { name: "Lead", stageType: "active", position: 0, color: "#6366f1" },
      { name: "Estimate Sent", stageType: "active", position: 1, color: "#3b82f6" },
      { name: "In Progress", stageType: "active", position: 2, color: "#f59e0b" },
      { name: "Completed", stageType: "completed", position: 3, color: "#22c55e" },
      { name: "Cancelled", stageType: "cancelled", position: 4, color: "#ef4444" },
    ],
    defaultTags: ["Residential", "Commercial", "High Value", "Repeat Customer", "Urgent"],
    agentProfile: {
      focusArea: "estimate conversion, job progress, and outstanding invoices",
      keyMetrics: ["open estimate value", "active jobs", "outstanding invoices", "job completion rate"],
      avoidLanguage: [],
    },
  },

  general_contractor: {
    id: "general_contractor",
    label: "General Contractor",
    headline: "GC project and bid management view",
    dailyFocus:
      "Track customers, bids, active projects, invoices, and subcontractor tasks.",
    labels: {
      customerSingular: "Customer",
      customerPlural: "Customers",
      leadSingular: "Bid",
      leadPlural: "Bids",
      jobSingular: "Project",
      jobPlural: "Projects",
      saleSingular: "Invoice",
      salePlural: "Invoices",
      followUpSingular: "Project task",
      followUpPlural: "Project tasks",
    },
    priorityNames: {
      pipeline: "Open bid value",
      activeWork: "Active projects",
      revenue: "Project revenue",
      followUps: "Project tasks due",
      dataHealth: "Project data quality",
    },
    insightPrompts: [
      "Which bids haven't had a response in over a week?",
      "Which projects have outstanding change orders or unpaid invoices?",
      "Which projects are missing a contract or signed scope?",
    ],
    pipelineLabel: "Project Board",
    recordLabel: "Project",
    recordPlural: "Projects",
    completedLabel: "Completed",
    cancelledLabel: "Cancelled",
    valueLabel: "Contract Value",
    invoiceLabel: "Invoice",
    targetDateLabel: "Target Completion",
    activeStatusLabel: "Active",
    inactiveStatusLabel: "On Hold",
    closedStatusLabel: "Closed",
    sourceOptions: ["Referral", "Website", "Bid Board", "Repeat Customer", "Architect / Designer", "Other"],
    defaultBoardName: "Project Board",
    defaultStages: [
      { name: "Bid", stageType: "active", position: 0, color: "#6366f1" },
      { name: "Awarded", stageType: "active", position: 1, color: "#3b82f6" },
      { name: "In Progress", stageType: "active", position: 2, color: "#f59e0b" },
      { name: "Punch List", stageType: "active", position: 3, color: "#8b5cf6" },
      { name: "Completed", stageType: "completed", position: 4, color: "#22c55e" },
      { name: "Cancelled", stageType: "cancelled", position: 5, color: "#ef4444" },
    ],
    defaultTags: ["Residential", "Commercial", "High Value", "Repeat Customer", "Bonded"],
    agentProfile: {
      focusArea: "bid pipeline, project milestones, and subcontractor coordination",
      keyMetrics: ["open bid value", "active projects", "outstanding invoices", "project margin"],
      avoidLanguage: [],
    },
  },

  electrical: {
    id: "electrical",
    label: "Electrical Contractor",
    headline: "Electrical jobs and service calls view",
    dailyFocus:
      "Track clients, service calls, jobs, quotes, and follow-ups for electrical contractors.",
    labels: {
      customerSingular: "Client",
      customerPlural: "Clients",
      leadSingular: "Quote",
      leadPlural: "Quotes",
      jobSingular: "Job",
      jobPlural: "Jobs",
      saleSingular: "Invoice",
      salePlural: "Invoices",
      followUpSingular: "Job task",
      followUpPlural: "Job tasks",
    },
    priorityNames: {
      pipeline: "Open quote value",
      activeWork: "Active jobs",
      revenue: "Job revenue",
      followUps: "Job tasks due",
      dataHealth: "Job data quality",
    },
    insightPrompts: [
      "Which quotes haven't had a response in over a week?",
      "Which jobs have unpaid invoices?",
      "Which jobs are missing a quote value or permit number?",
    ],
    pipelineLabel: "Job Board",
    recordLabel: "Job",
    recordPlural: "Jobs",
    completedLabel: "Completed",
    cancelledLabel: "Cancelled",
    valueLabel: "Quote Value",
    invoiceLabel: "Invoice",
    targetDateLabel: "Target Date",
    activeStatusLabel: "Active",
    inactiveStatusLabel: "Inactive",
    closedStatusLabel: "Closed",
    sourceOptions: ["Referral", "Website", "Repeat Customer", "Lead Service", "Builder / GC", "Other"],
    defaultBoardName: "Job Board",
    defaultStages: [
      { name: "Quote", stageType: "active", position: 0, color: "#6366f1" },
      { name: "Scheduled", stageType: "active", position: 1, color: "#3b82f6" },
      { name: "In Progress", stageType: "active", position: 2, color: "#f59e0b" },
      { name: "Completed", stageType: "completed", position: 3, color: "#22c55e" },
      { name: "Cancelled", stageType: "cancelled", position: 4, color: "#ef4444" },
    ],
    defaultTags: ["Residential", "Commercial", "Emergency", "Permit Required", "Repeat Client"],
    agentProfile: {
      focusArea: "quote conversion, job scheduling, and outstanding invoices",
      keyMetrics: ["open quote value", "active jobs", "outstanding invoices", "job completion rate"],
      avoidLanguage: [],
    },
  },

  plumbing: {
    id: "plumbing",
    label: "Plumbing Contractor",
    headline: "Plumbing jobs and service calls view",
    dailyFocus:
      "Track clients, service calls, jobs, quotes, and follow-ups for plumbing contractors.",
    labels: {
      customerSingular: "Client",
      customerPlural: "Clients",
      leadSingular: "Quote",
      leadPlural: "Quotes",
      jobSingular: "Job",
      jobPlural: "Jobs",
      saleSingular: "Invoice",
      salePlural: "Invoices",
      followUpSingular: "Job task",
      followUpPlural: "Job tasks",
    },
    priorityNames: {
      pipeline: "Open quote value",
      activeWork: "Active jobs",
      revenue: "Job revenue",
      followUps: "Job tasks due",
      dataHealth: "Job data quality",
    },
    insightPrompts: [
      "Which quotes haven't had a response in over a week?",
      "Which jobs have unpaid invoices?",
      "Which jobs are missing a scope or quote value?",
    ],
    pipelineLabel: "Job Board",
    recordLabel: "Job",
    recordPlural: "Jobs",
    completedLabel: "Completed",
    cancelledLabel: "Cancelled",
    valueLabel: "Quote Value",
    invoiceLabel: "Invoice",
    targetDateLabel: "Target Date",
    activeStatusLabel: "Active",
    inactiveStatusLabel: "Inactive",
    closedStatusLabel: "Closed",
    sourceOptions: ["Referral", "Website", "Repeat Customer", "Lead Service", "Property Manager", "Other"],
    defaultBoardName: "Job Board",
    defaultStages: [
      { name: "Quote", stageType: "active", position: 0, color: "#6366f1" },
      { name: "Scheduled", stageType: "active", position: 1, color: "#3b82f6" },
      { name: "In Progress", stageType: "active", position: 2, color: "#f59e0b" },
      { name: "Completed", stageType: "completed", position: 3, color: "#22c55e" },
      { name: "Cancelled", stageType: "cancelled", position: 4, color: "#ef4444" },
    ],
    defaultTags: ["Residential", "Commercial", "Emergency", "Repeat Client", "Property Manager"],
    agentProfile: {
      focusArea: "quote conversion, job scheduling, and outstanding invoices",
      keyMetrics: ["open quote value", "active jobs", "outstanding invoices", "emergency call rate"],
      avoidLanguage: [],
    },
  },

  hvac: {
    id: "hvac",
    label: "HVAC Contractor",
    headline: "HVAC service and installation view",
    dailyFocus:
      "Track clients, service calls, installations, quotes, and maintenance agreements.",
    labels: {
      customerSingular: "Client",
      customerPlural: "Clients",
      leadSingular: "Quote",
      leadPlural: "Quotes",
      jobSingular: "Job",
      jobPlural: "Jobs",
      saleSingular: "Invoice",
      salePlural: "Invoices",
      followUpSingular: "Job task",
      followUpPlural: "Job tasks",
    },
    priorityNames: {
      pipeline: "Open quote value",
      activeWork: "Active jobs",
      revenue: "Job revenue",
      followUps: "Job tasks due",
      dataHealth: "Job data quality",
    },
    insightPrompts: [
      "Which quotes for installations haven't had a response in over a week?",
      "Which clients are due for seasonal maintenance?",
      "Which jobs have outstanding invoices?",
    ],
    pipelineLabel: "Job Board",
    recordLabel: "Job",
    recordPlural: "Jobs",
    completedLabel: "Completed",
    cancelledLabel: "Cancelled",
    valueLabel: "Quote Value",
    invoiceLabel: "Invoice",
    targetDateLabel: "Target Date",
    activeStatusLabel: "Active",
    inactiveStatusLabel: "Inactive",
    closedStatusLabel: "Closed",
    sourceOptions: ["Referral", "Website", "Repeat Customer", "Lead Service", "Builder / GC", "Maintenance Agreement"],
    defaultBoardName: "Job Board",
    defaultStages: [
      { name: "Quote", stageType: "active", position: 0, color: "#6366f1" },
      { name: "Scheduled", stageType: "active", position: 1, color: "#3b82f6" },
      { name: "In Progress", stageType: "active", position: 2, color: "#f59e0b" },
      { name: "Completed", stageType: "completed", position: 3, color: "#22c55e" },
      { name: "Cancelled", stageType: "cancelled", position: 4, color: "#ef4444" },
    ],
    defaultTags: ["Residential", "Commercial", "Emergency", "Maintenance Agreement", "Repeat Client"],
    agentProfile: {
      focusArea: "installation pipeline, service scheduling, and maintenance agreement renewals",
      keyMetrics: ["open quote value", "active jobs", "maintenance agreements", "outstanding invoices"],
      avoidLanguage: [],
    },
  },

  roofing: {
    id: "roofing",
    label: "Roofing Contractor",
    headline: "Roofing projects and estimates view",
    dailyFocus:
      "Track customers, estimates, active projects, invoices, and insurance claims.",
    labels: {
      customerSingular: "Customer",
      customerPlural: "Customers",
      leadSingular: "Estimate",
      leadPlural: "Estimates",
      jobSingular: "Project",
      jobPlural: "Projects",
      saleSingular: "Invoice",
      salePlural: "Invoices",
      followUpSingular: "Project task",
      followUpPlural: "Project tasks",
    },
    priorityNames: {
      pipeline: "Open estimate value",
      activeWork: "Active projects",
      revenue: "Project revenue",
      followUps: "Project tasks due",
      dataHealth: "Project data quality",
    },
    insightPrompts: [
      "Which estimates haven't had a response in over a week?",
      "Which projects are pending insurance approval?",
      "Which projects have outstanding invoices?",
    ],
    pipelineLabel: "Project Board",
    recordLabel: "Project",
    recordPlural: "Projects",
    completedLabel: "Completed",
    cancelledLabel: "Cancelled",
    valueLabel: "Estimate Value",
    invoiceLabel: "Invoice",
    targetDateLabel: "Target Date",
    activeStatusLabel: "Active",
    inactiveStatusLabel: "Inactive",
    closedStatusLabel: "Closed",
    sourceOptions: ["Referral", "Door-to-Door", "Storm Lead", "Website", "Repeat Customer", "Insurance Adjuster"],
    defaultBoardName: "Project Board",
    defaultStages: [
      { name: "Lead", stageType: "active", position: 0, color: "#6366f1" },
      { name: "Estimate Sent", stageType: "active", position: 1, color: "#3b82f6" },
      { name: "Insurance Pending", stageType: "on_hold", position: 2, color: "#8b5cf6" },
      { name: "In Progress", stageType: "active", position: 3, color: "#f59e0b" },
      { name: "Completed", stageType: "completed", position: 4, color: "#22c55e" },
      { name: "Cancelled", stageType: "cancelled", position: 5, color: "#ef4444" },
    ],
    defaultTags: ["Insurance Claim", "Residential", "Commercial", "Storm Damage", "High Value"],
    agentProfile: {
      focusArea: "estimate pipeline, insurance claim status, and project completion",
      keyMetrics: ["open estimate value", "active projects", "insurance pending", "outstanding invoices"],
      avoidLanguage: [],
    },
  },

  home_services: {
    id: "home_services",
    label: "Home & Field Services",
    headline: "Service and scheduling view",
    dailyFocus:
      "Track clients, quotes, service visits, invoices, and follow-up tasks for HVAC, plumbing, landscaping, cleaning, electrical, pest control, and similar trades.",
    labels: {
      customerSingular: "Client",
      customerPlural: "Clients",
      leadSingular: "Quote",
      leadPlural: "Quotes",
      jobSingular: "Service visit",
      jobPlural: "Service visits",
      saleSingular: "Invoice",
      salePlural: "Invoices",
      followUpSingular: "Follow-up task",
      followUpPlural: "Follow-up tasks",
    },
    priorityNames: {
      pipeline: "Open quote value",
      activeWork: "Scheduled visits",
      revenue: "Service revenue",
      followUps: "Follow-up tasks due",
      dataHealth: "Client data quality",
    },
    insightPrompts: [
      "Which clients are due for a callback or re-quote?",
      "Which quotes haven't had a response in the past week?",
      "Which service visits have no invoice, or invoices that are unpaid?",
    ],
    pipelineLabel: "Service Board",
    recordLabel: "Service Agreement",
    recordPlural: "Service Agreements",
    completedLabel: "Completed",
    cancelledLabel: "Cancelled",
    valueLabel: "Quote Value",
    invoiceLabel: "Invoice",
    targetDateLabel: "Target Date",
    activeStatusLabel: "Active",
    inactiveStatusLabel: "Inactive",
    closedStatusLabel: "Closed",
    sourceOptions: ["Referral", "Website", "Door-to-Door", "Repeat Customer", "Lead Service", "Other"],
    defaultBoardName: "Service Board",
    defaultStages: [
      { name: "Quote", stageType: "active", position: 0, color: "#6366f1" },
      { name: "Scheduled", stageType: "active", position: 1, color: "#3b82f6" },
      { name: "In Progress", stageType: "active", position: 2, color: "#f59e0b" },
      { name: "Completed", stageType: "completed", position: 3, color: "#22c55e" },
      { name: "Cancelled", stageType: "cancelled", position: 4, color: "#ef4444" },
    ],
    defaultTags: ["Recurring", "One-Time", "High Value", "Repeat Client", "Urgent"],
    agentProfile: {
      focusArea: "quote conversion, service scheduling, and recurring client retention",
      keyMetrics: ["open quote value", "scheduled visits", "service revenue", "recurring clients"],
      avoidLanguage: [],
    },
  },

  landscaping: {
    id: "landscaping",
    label: "Landscaping",
    headline: "Landscaping contracts and service view",
    dailyFocus:
      "Track clients, proposals, contracts, service visits, and invoices.",
    labels: {
      customerSingular: "Client",
      customerPlural: "Clients",
      leadSingular: "Proposal",
      leadPlural: "Proposals",
      jobSingular: "Service visit",
      jobPlural: "Service visits",
      saleSingular: "Invoice",
      salePlural: "Invoices",
      followUpSingular: "Follow-up task",
      followUpPlural: "Follow-up tasks",
    },
    priorityNames: {
      pipeline: "Open proposal value",
      activeWork: "Active contracts",
      revenue: "Service revenue",
      followUps: "Follow-up tasks due",
      dataHealth: "Client data quality",
    },
    insightPrompts: [
      "Which proposals haven't had a response in the past week?",
      "Which contracts are up for renewal?",
      "Which clients have unpaid invoices?",
    ],
    pipelineLabel: "Contract Board",
    recordLabel: "Contract",
    recordPlural: "Contracts",
    completedLabel: "Completed",
    cancelledLabel: "Cancelled",
    valueLabel: "Contract Value",
    invoiceLabel: "Invoice",
    targetDateLabel: "Season End Date",
    activeStatusLabel: "Active",
    inactiveStatusLabel: "Inactive",
    closedStatusLabel: "Closed",
    sourceOptions: ["Referral", "Website", "Door-to-Door", "Repeat Client", "HOA / Property Manager", "Other"],
    defaultBoardName: "Contract Board",
    defaultStages: [
      { name: "Proposal", stageType: "active", position: 0, color: "#6366f1" },
      { name: "Scheduled", stageType: "active", position: 1, color: "#3b82f6" },
      { name: "Active Contract", stageType: "active", position: 2, color: "#f59e0b" },
      { name: "Completed", stageType: "completed", position: 3, color: "#22c55e" },
      { name: "Cancelled", stageType: "cancelled", position: 4, color: "#ef4444" },
    ],
    defaultTags: ["Recurring", "One-Time", "Commercial", "Residential", "HOA"],
    agentProfile: {
      focusArea: "contract pipeline, seasonal scheduling, and recurring revenue",
      keyMetrics: ["open proposal value", "active contracts", "recurring clients", "outstanding invoices"],
      avoidLanguage: [],
    },
  },

  cleaning: {
    id: "cleaning",
    label: "Cleaning Services",
    headline: "Cleaning service and scheduling view",
    dailyFocus:
      "Track clients, proposals, service agreements, cleanings, and invoices.",
    labels: {
      customerSingular: "Client",
      customerPlural: "Clients",
      leadSingular: "Proposal",
      leadPlural: "Proposals",
      jobSingular: "Cleaning",
      jobPlural: "Cleanings",
      saleSingular: "Invoice",
      salePlural: "Invoices",
      followUpSingular: "Follow-up task",
      followUpPlural: "Follow-up tasks",
    },
    priorityNames: {
      pipeline: "Open proposal value",
      activeWork: "Scheduled cleanings",
      revenue: "Service revenue",
      followUps: "Follow-up tasks due",
      dataHealth: "Client data quality",
    },
    insightPrompts: [
      "Which proposals haven't been followed up on this week?",
      "Which clients are missing a recurring schedule?",
      "Which invoices are outstanding or overdue?",
    ],
    pipelineLabel: "Service Board",
    recordLabel: "Service Agreement",
    recordPlural: "Service Agreements",
    completedLabel: "Completed",
    cancelledLabel: "Cancelled",
    valueLabel: "Agreement Value",
    invoiceLabel: "Invoice",
    targetDateLabel: "Next Service Date",
    activeStatusLabel: "Active",
    inactiveStatusLabel: "Inactive",
    closedStatusLabel: "Closed",
    sourceOptions: ["Referral", "Website", "Door-to-Door", "Repeat Client", "Property Manager", "Other"],
    defaultBoardName: "Service Board",
    defaultStages: [
      { name: "Proposal", stageType: "active", position: 0, color: "#6366f1" },
      { name: "Scheduled", stageType: "active", position: 1, color: "#3b82f6" },
      { name: "Active Agreement", stageType: "active", position: 2, color: "#f59e0b" },
      { name: "Completed", stageType: "completed", position: 3, color: "#22c55e" },
      { name: "Cancelled", stageType: "cancelled", position: 4, color: "#ef4444" },
    ],
    defaultTags: ["Recurring", "One-Time", "Commercial", "Residential", "Move-In/Out"],
    agentProfile: {
      focusArea: "service agreement pipeline, recurring schedule, and client retention",
      keyMetrics: ["open proposal value", "recurring clients", "service revenue", "outstanding invoices"],
      avoidLanguage: [],
    },
  },

  pest_control: {
    id: "pest_control",
    label: "Pest Control",
    headline: "Pest control service and scheduling view",
    dailyFocus:
      "Track clients, proposals, service plans, service visits, and invoices.",
    labels: {
      customerSingular: "Client",
      customerPlural: "Clients",
      leadSingular: "Proposal",
      leadPlural: "Proposals",
      jobSingular: "Service visit",
      jobPlural: "Service visits",
      saleSingular: "Invoice",
      salePlural: "Invoices",
      followUpSingular: "Follow-up task",
      followUpPlural: "Follow-up tasks",
    },
    priorityNames: {
      pipeline: "Open proposal value",
      activeWork: "Scheduled visits",
      revenue: "Service revenue",
      followUps: "Follow-up tasks due",
      dataHealth: "Client data quality",
    },
    insightPrompts: [
      "Which clients are due for their next service visit?",
      "Which proposals haven't been followed up on?",
      "Which invoices are outstanding or overdue?",
    ],
    pipelineLabel: "Service Board",
    recordLabel: "Service Plan",
    recordPlural: "Service Plans",
    completedLabel: "Completed",
    cancelledLabel: "Cancelled",
    valueLabel: "Plan Value",
    invoiceLabel: "Invoice",
    targetDateLabel: "Next Service Date",
    activeStatusLabel: "Active",
    inactiveStatusLabel: "Inactive",
    closedStatusLabel: "Closed",
    sourceOptions: ["Referral", "Website", "Door-to-Door", "Repeat Client", "Property Manager", "Other"],
    defaultBoardName: "Service Board",
    defaultStages: [
      { name: "Proposal", stageType: "active", position: 0, color: "#6366f1" },
      { name: "Initial Treatment", stageType: "active", position: 1, color: "#3b82f6" },
      { name: "Active Plan", stageType: "active", position: 2, color: "#f59e0b" },
      { name: "Completed", stageType: "completed", position: 3, color: "#22c55e" },
      { name: "Cancelled", stageType: "cancelled", position: 4, color: "#ef4444" },
    ],
    defaultTags: ["Recurring", "One-Time", "Residential", "Commercial", "Emergency"],
    agentProfile: {
      focusArea: "service plan pipeline, recurring visit scheduling, and client retention",
      keyMetrics: ["open proposal value", "active plans", "service revenue", "outstanding invoices"],
      avoidLanguage: [],
    },
  },

  painting: {
    id: "painting",
    label: "Painting Contractor",
    headline: "Painting projects and estimates view",
    dailyFocus:
      "Track clients, estimates, active projects, and invoices for painting contractors.",
    labels: {
      customerSingular: "Client",
      customerPlural: "Clients",
      leadSingular: "Estimate",
      leadPlural: "Estimates",
      jobSingular: "Project",
      jobPlural: "Projects",
      saleSingular: "Invoice",
      salePlural: "Invoices",
      followUpSingular: "Project task",
      followUpPlural: "Project tasks",
    },
    priorityNames: {
      pipeline: "Open estimate value",
      activeWork: "Active projects",
      revenue: "Project revenue",
      followUps: "Project tasks due",
      dataHealth: "Project data quality",
    },
    insightPrompts: [
      "Which estimates haven't had a response in over a week?",
      "Which projects have outstanding invoices?",
      "Which projects are missing a scope or start date?",
    ],
    pipelineLabel: "Project Board",
    recordLabel: "Project",
    recordPlural: "Projects",
    completedLabel: "Completed",
    cancelledLabel: "Cancelled",
    valueLabel: "Estimate Value",
    invoiceLabel: "Invoice",
    targetDateLabel: "Target Date",
    activeStatusLabel: "Active",
    inactiveStatusLabel: "Inactive",
    closedStatusLabel: "Closed",
    sourceOptions: ["Referral", "Website", "Door-to-Door", "Repeat Client", "Builder / GC", "Other"],
    defaultBoardName: "Project Board",
    defaultStages: [
      { name: "Estimate", stageType: "active", position: 0, color: "#6366f1" },
      { name: "Scheduled", stageType: "active", position: 1, color: "#3b82f6" },
      { name: "In Progress", stageType: "active", position: 2, color: "#f59e0b" },
      { name: "Completed", stageType: "completed", position: 3, color: "#22c55e" },
      { name: "Cancelled", stageType: "cancelled", position: 4, color: "#ef4444" },
    ],
    defaultTags: ["Residential", "Commercial", "Interior", "Exterior", "Repeat Client"],
    agentProfile: {
      focusArea: "estimate conversion, project scheduling, and outstanding invoices",
      keyMetrics: ["open estimate value", "active projects", "outstanding invoices", "project completion rate"],
      avoidLanguage: [],
    },
  },

  professional_services: {
    id: "professional_services",
    label: "Professional Services",
    headline: "Client work and pipeline view",
    dailyFocus:
      "Track clients, proposals, active projects, invoices, and action items for consultants, agencies, accountants, lawyers, IT firms, and similar practices.",
    labels: {
      customerSingular: "Client",
      customerPlural: "Clients",
      leadSingular: "Proposal",
      leadPlural: "Proposals",
      jobSingular: "Project",
      jobPlural: "Projects",
      saleSingular: "Invoice",
      salePlural: "Invoices",
      followUpSingular: "Action item",
      followUpPlural: "Action items",
    },
    priorityNames: {
      pipeline: "Proposal pipeline",
      activeWork: "Active projects",
      revenue: "Billed revenue",
      followUps: "Action items due",
      dataHealth: "Client data quality",
    },
    insightPrompts: [
      "Which proposals haven't had a response in over five business days?",
      "Which clients are past payment terms or approaching 30 days outstanding?",
      "Which active projects are missing scope, rate, or next milestone details?",
    ],
    pipelineLabel: "Pipeline",
    recordLabel: "Engagement",
    recordPlural: "Engagements",
    completedLabel: "Delivered",
    cancelledLabel: "Cancelled",
    valueLabel: "Engagement Value",
    invoiceLabel: "Invoice",
    targetDateLabel: "Due Date",
    activeStatusLabel: "Active",
    inactiveStatusLabel: "Inactive",
    closedStatusLabel: "Closed",
    sourceOptions: ["Referral", "Website", "Conference / Event", "LinkedIn", "Repeat Client", "Other"],
    defaultBoardName: "Pipeline",
    defaultStages: [
      { name: "Proposal", stageType: "active", position: 0, color: "#6366f1" },
      { name: "Negotiation", stageType: "active", position: 1, color: "#3b82f6" },
      { name: "Active", stageType: "active", position: 2, color: "#f59e0b" },
      { name: "Delivered", stageType: "completed", position: 3, color: "#22c55e" },
      { name: "Cancelled", stageType: "cancelled", position: 4, color: "#ef4444" },
    ],
    defaultTags: ["High Value", "Retainer", "One-Time", "Repeat Client", "Strategic"],
    agentProfile: {
      focusArea: "proposal pipeline, active engagement delivery, and outstanding invoices",
      keyMetrics: ["proposal pipeline value", "active engagements", "billed revenue", "outstanding invoices"],
      avoidLanguage: [],
    },
  },

  legal: {
    id: "legal",
    label: "Legal Practice",
    headline: "Law firm matters and case management view",
    dailyFocus:
      "Track clients, matters, deadlines, billing, and case activity for law firms.",
    labels: {
      customerSingular: "Client",
      customerPlural: "Clients",
      leadSingular: "Matter",
      leadPlural: "Matters",
      jobSingular: "Matter",
      jobPlural: "Matters",
      saleSingular: "Bill",
      salePlural: "Bills",
      followUpSingular: "Action item",
      followUpPlural: "Action items",
    },
    priorityNames: {
      pipeline: "Matter value",
      activeWork: "Active matters",
      revenue: "Billed revenue",
      followUps: "Deadlines due",
      dataHealth: "Matter completeness",
    },
    insightPrompts: [
      "Which matters have upcoming deadlines in the next 7 days?",
      "Which clients have outstanding bills past 30 days?",
      "Which matters are missing key details like opposing counsel or case number?",
    ],
    pipelineLabel: "Case Board",
    recordLabel: "Matter",
    recordPlural: "Matters",
    completedLabel: "Closed",
    cancelledLabel: "Dismissed",
    valueLabel: "Matter Value",
    invoiceLabel: "Bill",
    targetDateLabel: "Expected Resolution",
    activeStatusLabel: "Active",
    inactiveStatusLabel: "Inactive",
    closedStatusLabel: "Closed",
    sourceOptions: ["Referral", "Website", "Bar Referral", "Repeat Client", "Legal Aid", "Other"],
    defaultBoardName: "Case Board",
    defaultStages: [
      { name: "Intake", stageType: "active", position: 0, color: "#6366f1" },
      { name: "Investigation", stageType: "active", position: 1, color: "#3b82f6" },
      { name: "Active Litigation", stageType: "active", position: 2, color: "#f59e0b" },
      { name: "Settlement / Resolution", stageType: "active", position: 3, color: "#8b5cf6" },
      { name: "Closed", stageType: "completed", position: 4, color: "#22c55e" },
      { name: "Dismissed", stageType: "cancelled", position: 5, color: "#ef4444" },
    ],
    defaultTags: ["High Value", "Contingency", "Retainer", "Statute Approaching", "Pro Bono"],
    agentProfile: {
      focusArea: "matter status, upcoming deadlines, and billing realization",
      keyMetrics: ["active matters", "upcoming deadlines", "billed vs collected", "matter aging"],
      avoidLanguage: ["win rate", "close date", "deal", "prospect", "sale", "revenue"],
    },
  },

  accounting: {
    id: "accounting",
    label: "Accounting Practice",
    headline: "Accounting engagements and client work view",
    dailyFocus:
      "Track clients, engagements, deadlines, billing, and deliverables for accounting firms.",
    labels: {
      customerSingular: "Client",
      customerPlural: "Clients",
      leadSingular: "Engagement",
      leadPlural: "Engagements",
      jobSingular: "Engagement",
      jobPlural: "Engagements",
      saleSingular: "Invoice",
      salePlural: "Invoices",
      followUpSingular: "Action item",
      followUpPlural: "Action items",
    },
    priorityNames: {
      pipeline: "Engagement pipeline",
      activeWork: "Active engagements",
      revenue: "Billed revenue",
      followUps: "Deadlines due",
      dataHealth: "Client data quality",
    },
    insightPrompts: [
      "Which clients have upcoming filing deadlines in the next 30 days?",
      "Which engagements have outstanding invoices past 30 days?",
      "Which clients are missing documents needed to complete their engagement?",
    ],
    pipelineLabel: "Engagement Board",
    recordLabel: "Engagement",
    recordPlural: "Engagements",
    completedLabel: "Delivered",
    cancelledLabel: "Cancelled",
    valueLabel: "Engagement Value",
    invoiceLabel: "Invoice",
    targetDateLabel: "Filing Deadline",
    activeStatusLabel: "Active",
    inactiveStatusLabel: "Inactive",
    closedStatusLabel: "Closed",
    sourceOptions: ["Referral", "Website", "Networking", "Repeat Client", "Partner Referral", "Other"],
    defaultBoardName: "Engagement Board",
    defaultStages: [
      { name: "Proposal", stageType: "active", position: 0, color: "#6366f1" },
      { name: "Document Collection", stageType: "active", position: 1, color: "#3b82f6" },
      { name: "In Progress", stageType: "active", position: 2, color: "#f59e0b" },
      { name: "Review", stageType: "active", position: 3, color: "#8b5cf6" },
      { name: "Delivered", stageType: "completed", position: 4, color: "#22c55e" },
      { name: "Cancelled", stageType: "cancelled", position: 5, color: "#ef4444" },
    ],
    defaultTags: ["Tax", "Audit", "Advisory", "Bookkeeping", "High Value"],
    agentProfile: {
      focusArea: "engagement delivery, deadline compliance, and billing realization",
      keyMetrics: ["active engagements", "upcoming deadlines", "billed revenue", "outstanding invoices"],
      avoidLanguage: ["win rate", "deal", "prospect", "sale"],
    },
  },

  consulting: {
    id: "consulting",
    label: "Consulting",
    headline: "Consulting engagements and project pipeline view",
    dailyFocus:
      "Track clients, proposals, active engagements, milestones, and invoices.",
    labels: {
      customerSingular: "Client",
      customerPlural: "Clients",
      leadSingular: "Proposal",
      leadPlural: "Proposals",
      jobSingular: "Engagement",
      jobPlural: "Engagements",
      saleSingular: "Invoice",
      salePlural: "Invoices",
      followUpSingular: "Action item",
      followUpPlural: "Action items",
    },
    priorityNames: {
      pipeline: "Proposal pipeline",
      activeWork: "Active engagements",
      revenue: "Billed revenue",
      followUps: "Action items due",
      dataHealth: "Client data quality",
    },
    insightPrompts: [
      "Which proposals haven't had a response in over five business days?",
      "Which engagements have upcoming milestones this week?",
      "Which clients have outstanding invoices past 30 days?",
    ],
    pipelineLabel: "Pipeline",
    recordLabel: "Engagement",
    recordPlural: "Engagements",
    completedLabel: "Delivered",
    cancelledLabel: "Cancelled",
    valueLabel: "Engagement Value",
    invoiceLabel: "Invoice",
    targetDateLabel: "Due Date",
    activeStatusLabel: "Active",
    inactiveStatusLabel: "Inactive",
    closedStatusLabel: "Closed",
    sourceOptions: ["Referral", "Website", "Conference / Event", "LinkedIn", "Repeat Client", "Other"],
    defaultBoardName: "Pipeline",
    defaultStages: [
      { name: "Proposal", stageType: "active", position: 0, color: "#6366f1" },
      { name: "Negotiation", stageType: "active", position: 1, color: "#3b82f6" },
      { name: "Active", stageType: "active", position: 2, color: "#f59e0b" },
      { name: "Delivered", stageType: "completed", position: 3, color: "#22c55e" },
      { name: "Cancelled", stageType: "cancelled", position: 4, color: "#ef4444" },
    ],
    defaultTags: ["High Value", "Retainer", "Project-Based", "Strategic", "Repeat Client"],
    agentProfile: {
      focusArea: "proposal pipeline, engagement delivery, and client expansion",
      keyMetrics: ["proposal pipeline value", "active engagements", "billed revenue", "client retention"],
      avoidLanguage: [],
    },
  },

  agency: {
    id: "agency",
    label: "Agency",
    headline: "Agency campaigns and client work view",
    dailyFocus:
      "Track clients, proposals, active campaigns and projects, deliverables, and invoices.",
    labels: {
      customerSingular: "Client",
      customerPlural: "Clients",
      leadSingular: "Proposal",
      leadPlural: "Proposals",
      jobSingular: "Campaign",
      jobPlural: "Campaigns",
      saleSingular: "Invoice",
      salePlural: "Invoices",
      followUpSingular: "Action item",
      followUpPlural: "Action items",
    },
    priorityNames: {
      pipeline: "Proposal pipeline",
      activeWork: "Active campaigns",
      revenue: "Billed revenue",
      followUps: "Action items due",
      dataHealth: "Client data quality",
    },
    insightPrompts: [
      "Which proposals haven't had a response in over five business days?",
      "Which campaigns have deliverables due this week?",
      "Which clients have outstanding invoices past 30 days?",
    ],
    pipelineLabel: "Pipeline",
    recordLabel: "Campaign",
    recordPlural: "Campaigns",
    completedLabel: "Delivered",
    cancelledLabel: "Cancelled",
    valueLabel: "Campaign Value",
    invoiceLabel: "Invoice",
    targetDateLabel: "Due Date",
    activeStatusLabel: "Active",
    inactiveStatusLabel: "Inactive",
    closedStatusLabel: "Closed",
    sourceOptions: ["Referral", "Website", "Conference / Event", "LinkedIn", "Repeat Client", "Other"],
    defaultBoardName: "Pipeline",
    defaultStages: [
      { name: "Proposal", stageType: "active", position: 0, color: "#6366f1" },
      { name: "Kickoff", stageType: "active", position: 1, color: "#3b82f6" },
      { name: "In Flight", stageType: "active", position: 2, color: "#f59e0b" },
      { name: "Delivered", stageType: "completed", position: 3, color: "#22c55e" },
      { name: "Cancelled", stageType: "cancelled", position: 4, color: "#ef4444" },
    ],
    defaultTags: ["Retainer", "Project-Based", "High Value", "Repeat Client", "New Logo"],
    agentProfile: {
      focusArea: "proposal pipeline, campaign delivery, and client retention",
      keyMetrics: ["proposal pipeline value", "active campaigns", "billed revenue", "client churn risk"],
      avoidLanguage: [],
    },
  },

  it_services: {
    id: "it_services",
    label: "IT Services",
    headline: "IT projects and managed services view",
    dailyFocus:
      "Track clients, proposals, active projects, support tickets, and invoices.",
    labels: {
      customerSingular: "Client",
      customerPlural: "Clients",
      leadSingular: "Proposal",
      leadPlural: "Proposals",
      jobSingular: "Project",
      jobPlural: "Projects",
      saleSingular: "Invoice",
      salePlural: "Invoices",
      followUpSingular: "Action item",
      followUpPlural: "Action items",
    },
    priorityNames: {
      pipeline: "Proposal pipeline",
      activeWork: "Active projects",
      revenue: "Billed revenue",
      followUps: "Action items due",
      dataHealth: "Client data quality",
    },
    insightPrompts: [
      "Which proposals haven't had a response in over five business days?",
      "Which projects have open critical tickets?",
      "Which clients have outstanding invoices past 30 days?",
    ],
    pipelineLabel: "Project Board",
    recordLabel: "Project",
    recordPlural: "Projects",
    completedLabel: "Delivered",
    cancelledLabel: "Cancelled",
    valueLabel: "Project Value",
    invoiceLabel: "Invoice",
    targetDateLabel: "Target Date",
    activeStatusLabel: "Active",
    inactiveStatusLabel: "Inactive",
    closedStatusLabel: "Closed",
    sourceOptions: ["Referral", "Website", "MSP Marketplace", "Repeat Client", "LinkedIn", "Other"],
    defaultBoardName: "Project Board",
    defaultStages: [
      { name: "Proposal", stageType: "active", position: 0, color: "#6366f1" },
      { name: "Kickoff", stageType: "active", position: 1, color: "#3b82f6" },
      { name: "In Progress", stageType: "active", position: 2, color: "#f59e0b" },
      { name: "UAT / Review", stageType: "active", position: 3, color: "#8b5cf6" },
      { name: "Delivered", stageType: "completed", position: 4, color: "#22c55e" },
      { name: "Cancelled", stageType: "cancelled", position: 5, color: "#ef4444" },
    ],
    defaultTags: ["MSP", "Project-Based", "High Value", "Repeat Client", "Security"],
    agentProfile: {
      focusArea: "project pipeline, managed service health, and billing realization",
      keyMetrics: ["proposal pipeline value", "active projects", "billed revenue", "outstanding invoices"],
      avoidLanguage: [],
    },
  },

  financial_advisory: {
    id: "financial_advisory",
    label: "Financial Advisory",
    headline: "Financial advisory engagements and AUM view",
    dailyFocus:
      "Track clients, engagements, portfolio value, reviews, and compliance tasks.",
    labels: {
      customerSingular: "Client",
      customerPlural: "Clients",
      leadSingular: "Engagement",
      leadPlural: "Engagements",
      jobSingular: "Engagement",
      jobPlural: "Engagements",
      saleSingular: "Invoice",
      salePlural: "Invoices",
      followUpSingular: "Action item",
      followUpPlural: "Action items",
    },
    priorityNames: {
      pipeline: "Engagement pipeline",
      activeWork: "Active clients",
      revenue: "Advisory fees",
      followUps: "Action items due",
      dataHealth: "Client data quality",
    },
    insightPrompts: [
      "Which clients haven't had a portfolio review in the past quarter?",
      "Which prospects haven't responded to an engagement proposal?",
      "Which clients are missing beneficiary or compliance documentation?",
    ],
    pipelineLabel: "Pipeline",
    recordLabel: "Engagement",
    recordPlural: "Engagements",
    completedLabel: "Completed",
    cancelledLabel: "Cancelled",
    valueLabel: "Portfolio Value",
    invoiceLabel: "Invoice",
    targetDateLabel: "Review Date",
    activeStatusLabel: "Active",
    inactiveStatusLabel: "Inactive",
    closedStatusLabel: "Closed",
    sourceOptions: ["Referral", "Seminar / Event", "LinkedIn", "CPA Referral", "Attorney Referral", "Other"],
    defaultBoardName: "Pipeline",
    defaultStages: [
      { name: "Prospect", stageType: "active", position: 0, color: "#6366f1" },
      { name: "Discovery", stageType: "active", position: 1, color: "#3b82f6" },
      { name: "Proposal Sent", stageType: "active", position: 2, color: "#f59e0b" },
      { name: "Active Client", stageType: "active", position: 3, color: "#22c55e" },
      { name: "Completed", stageType: "completed", position: 4, color: "#6b7280" },
      { name: "Cancelled", stageType: "cancelled", position: 5, color: "#ef4444" },
    ],
    defaultTags: ["High Net Worth", "Retirement", "Business Owner", "Referral Source", "Complex"],
    agentProfile: {
      focusArea: "AUM growth, client review compliance, and referral pipeline",
      keyMetrics: ["total AUM", "active clients", "annual fees", "review completion rate"],
      avoidLanguage: ["win rate", "close date", "deal"],
    },
  },

  fitness: {
    id: "fitness",
    label: "Fitness & Wellness",
    headline: "Fitness studio and gym member management view",
    dailyFocus:
      "Track members, programs, sessions, renewals, and engagement for fitness businesses.",
    labels: {
      customerSingular: "Member",
      customerPlural: "Members",
      leadSingular: "Program",
      leadPlural: "Programs",
      jobSingular: "Session",
      jobPlural: "Sessions",
      saleSingular: "Payment",
      salePlural: "Payments",
      followUpSingular: "Follow-up",
      followUpPlural: "Follow-ups",
    },
    priorityNames: {
      pipeline: "Program pipeline",
      activeWork: "Active members",
      revenue: "Membership revenue",
      followUps: "Follow-ups due",
      dataHealth: "Member data quality",
    },
    insightPrompts: [
      "Which members haven't attended a session in the past two weeks?",
      "Which memberships are up for renewal in the next 30 days?",
      "Which prospects haven't converted after a trial?",
    ],
    pipelineLabel: "Member Journey",
    recordLabel: "Program",
    recordPlural: "Programs",
    completedLabel: "Completed",
    cancelledLabel: "Cancelled",
    valueLabel: "Program Value",
    invoiceLabel: "Invoice",
    targetDateLabel: "End Date",
    activeStatusLabel: "Active",
    inactiveStatusLabel: "Lapsed",
    closedStatusLabel: "Cancelled",
    sourceOptions: ["Referral", "Website", "Social Media", "Walk-in", "Free Trial", "Other"],
    defaultBoardName: "Member Journey",
    defaultStages: [
      { name: "Prospect", stageType: "active", position: 0, color: "#6366f1" },
      { name: "Trial", stageType: "active", position: 1, color: "#3b82f6" },
      { name: "Active Member", stageType: "active", position: 2, color: "#22c55e" },
      { name: "At Risk", stageType: "on_hold", position: 3, color: "#f59e0b" },
      { name: "Completed", stageType: "completed", position: 4, color: "#6b7280" },
      { name: "Cancelled", stageType: "cancelled", position: 5, color: "#ef4444" },
    ],
    defaultTags: ["New Member", "High Value", "Renewal Due", "At Risk", "Referral Source"],
    agentProfile: {
      focusArea: "member retention, program enrollment, and renewal pipeline",
      keyMetrics: ["active members", "attendance rate", "renewal rate", "membership revenue"],
      avoidLanguage: ["win rate", "close date", "deal"],
    },
  },

  photography: {
    id: "photography",
    label: "Photography",
    headline: "Photography bookings and client sessions view",
    dailyFocus:
      "Track clients, bookings, sessions, deliverables, and invoices.",
    labels: {
      customerSingular: "Client",
      customerPlural: "Clients",
      leadSingular: "Inquiry",
      leadPlural: "Inquiries",
      jobSingular: "Booking",
      jobPlural: "Bookings",
      saleSingular: "Invoice",
      salePlural: "Invoices",
      followUpSingular: "Follow-up",
      followUpPlural: "Follow-ups",
    },
    priorityNames: {
      pipeline: "Inquiry pipeline",
      activeWork: "Upcoming bookings",
      revenue: "Booking revenue",
      followUps: "Follow-ups due",
      dataHealth: "Client data quality",
    },
    insightPrompts: [
      "Which inquiries haven't been followed up on in the past 48 hours?",
      "Which bookings have deliverables that haven't been sent yet?",
      "Which clients have outstanding invoices?",
    ],
    pipelineLabel: "Booking Board",
    recordLabel: "Booking",
    recordPlural: "Bookings",
    completedLabel: "Delivered",
    cancelledLabel: "Cancelled",
    valueLabel: "Booking Value",
    invoiceLabel: "Invoice",
    targetDateLabel: "Session Date",
    activeStatusLabel: "Active",
    inactiveStatusLabel: "Inactive",
    closedStatusLabel: "Closed",
    sourceOptions: ["Referral", "Website", "Instagram", "Wedding Platform", "Repeat Client", "Other"],
    defaultBoardName: "Booking Board",
    defaultStages: [
      { name: "Inquiry", stageType: "active", position: 0, color: "#6366f1" },
      { name: "Proposal Sent", stageType: "active", position: 1, color: "#3b82f6" },
      { name: "Booked", stageType: "active", position: 2, color: "#f59e0b" },
      { name: "Session Complete", stageType: "active", position: 3, color: "#8b5cf6" },
      { name: "Delivered", stageType: "completed", position: 4, color: "#22c55e" },
      { name: "Cancelled", stageType: "cancelled", position: 5, color: "#ef4444" },
    ],
    defaultTags: ["Wedding", "Portrait", "Commercial", "Event", "High Value"],
    agentProfile: {
      focusArea: "inquiry response, booking pipeline, and delivery completion",
      keyMetrics: ["inquiry conversion rate", "upcoming bookings", "booking revenue", "outstanding invoices"],
      avoidLanguage: [],
    },
  },

  beauty: {
    id: "beauty",
    label: "Beauty & Salon",
    headline: "Salon and beauty service booking view",
    dailyFocus:
      "Track clients, appointments, services, and revenue for salons, spas, and beauty businesses.",
    labels: {
      customerSingular: "Client",
      customerPlural: "Clients",
      leadSingular: "Inquiry",
      leadPlural: "Inquiries",
      jobSingular: "Appointment",
      jobPlural: "Appointments",
      saleSingular: "Payment",
      salePlural: "Payments",
      followUpSingular: "Follow-up",
      followUpPlural: "Follow-ups",
    },
    priorityNames: {
      pipeline: "Booking pipeline",
      activeWork: "Upcoming appointments",
      revenue: "Service revenue",
      followUps: "Follow-ups due",
      dataHealth: "Client data quality",
    },
    insightPrompts: [
      "Which clients haven't booked in the past 60 days?",
      "Which clients are due for their next appointment?",
      "Which inquiries haven't been converted to bookings?",
    ],
    pipelineLabel: "Booking Board",
    recordLabel: "Appointment",
    recordPlural: "Appointments",
    completedLabel: "Completed",
    cancelledLabel: "Cancelled",
    valueLabel: "Service Value",
    invoiceLabel: "Receipt",
    targetDateLabel: "Appointment Date",
    activeStatusLabel: "Active",
    inactiveStatusLabel: "Lapsed",
    closedStatusLabel: "Closed",
    sourceOptions: ["Referral", "Website", "Instagram", "Walk-in", "Repeat Client", "Other"],
    defaultBoardName: "Booking Board",
    defaultStages: [
      { name: "Inquiry", stageType: "active", position: 0, color: "#6366f1" },
      { name: "Booked", stageType: "active", position: 1, color: "#3b82f6" },
      { name: "Completed", stageType: "completed", position: 2, color: "#22c55e" },
      { name: "Cancelled", stageType: "cancelled", position: 3, color: "#ef4444" },
    ],
    defaultTags: ["VIP", "Recurring", "New Client", "Lapsed", "High Value"],
    agentProfile: {
      focusArea: "booking pipeline, client retention, and rebooking rate",
      keyMetrics: ["upcoming appointments", "rebooking rate", "service revenue", "lapsed clients"],
      avoidLanguage: ["win rate", "close date", "deal", "prospect"],
    },
  },

  auto_repair: {
    id: "auto_repair",
    label: "Auto Repair",
    headline: "Auto repair shop and service order view",
    dailyFocus:
      "Track customers, repair orders, estimates, service jobs, and invoices.",
    labels: {
      customerSingular: "Customer",
      customerPlural: "Customers",
      leadSingular: "Estimate",
      leadPlural: "Estimates",
      jobSingular: "Repair order",
      jobPlural: "Repair orders",
      saleSingular: "Invoice",
      salePlural: "Invoices",
      followUpSingular: "Follow-up",
      followUpPlural: "Follow-ups",
    },
    priorityNames: {
      pipeline: "Open estimate value",
      activeWork: "Active repair orders",
      revenue: "Shop revenue",
      followUps: "Follow-ups due",
      dataHealth: "Customer data quality",
    },
    insightPrompts: [
      "Which estimates haven't been approved in the past 48 hours?",
      "Which repair orders are waiting on parts or approvals?",
      "Which customers haven't returned in the past 6 months?",
    ],
    pipelineLabel: "Service Board",
    recordLabel: "Repair Order",
    recordPlural: "Repair Orders",
    completedLabel: "Completed",
    cancelledLabel: "Cancelled",
    valueLabel: "Estimate",
    invoiceLabel: "Invoice",
    targetDateLabel: "Promised Date",
    activeStatusLabel: "Active",
    inactiveStatusLabel: "Inactive",
    closedStatusLabel: "Closed",
    sourceOptions: ["Referral", "Website", "Walk-in", "Repeat Customer", "Fleet Account", "Other"],
    defaultBoardName: "Service Board",
    defaultStages: [
      { name: "Check-In", stageType: "active", position: 0, color: "#6366f1" },
      { name: "Estimate Sent", stageType: "active", position: 1, color: "#3b82f6" },
      { name: "Approved - In Shop", stageType: "active", position: 2, color: "#f59e0b" },
      { name: "Waiting on Parts", stageType: "on_hold", position: 3, color: "#8b5cf6" },
      { name: "Completed", stageType: "completed", position: 4, color: "#22c55e" },
      { name: "Cancelled", stageType: "cancelled", position: 5, color: "#ef4444" },
    ],
    defaultTags: ["Fleet", "Repeat Customer", "Warranty", "High Value", "Waiting on Parts"],
    agentProfile: {
      focusArea: "estimate approval, repair order throughput, and customer return rate",
      keyMetrics: ["open estimates", "active repair orders", "shop revenue", "outstanding invoices"],
      avoidLanguage: [],
    },
  },

  insurance: {
    id: "insurance",
    label: "Insurance",
    headline: "Client pipeline and policy tracking",
    dailyFocus:
      "Track clients, policy applications, renewals, and follow-up for insurance agencies and brokers.",
    labels: {
      customerSingular: "Client",
      customerPlural: "Clients",
      leadSingular: "Prospect",
      leadPlural: "Prospects",
      jobSingular: "Appointment",
      jobPlural: "Appointments",
      saleSingular: "Premium",
      salePlural: "Premiums",
      followUpSingular: "Follow-up",
      followUpPlural: "Follow-ups",
    },
    priorityNames: {
      pipeline: "Policy Pipeline",
      activeWork: "Active appointments",
      revenue: "Premium volume",
      followUps: "Follow-ups due",
      dataHealth: "Client data quality",
    },
    insightPrompts: [
      "Which clients have policies coming up for renewal in the next 30 days?",
      "Which prospects haven't responded to a quote in over a week?",
      "Which clients are missing contact details or policy numbers?",
    ],
    pipelineLabel: "Policy Pipeline",
    recordLabel: "Policy",
    recordPlural: "Policies",
    completedLabel: "Bound",
    cancelledLabel: "Declined",
    valueLabel: "Premium Value",
    invoiceLabel: "Invoice",
    targetDateLabel: "Effective Date",
    activeStatusLabel: "Active",
    inactiveStatusLabel: "Inactive",
    closedStatusLabel: "Closed",
    sourceOptions: ["Referral", "Website", "Cold Call", "Social Media", "Agent Network", "Walk-in"],
    defaultBoardName: "Policy Pipeline",
    defaultStages: [
      { name: "Prospect", stageType: "active", position: 1, color: "#6B7280" },
      { name: "Quoting", stageType: "active", position: 2, color: "#3B82F6" },
      { name: "Application", stageType: "active", position: 3, color: "#8B5CF6" },
      { name: "Bound", stageType: "completed", position: 4, color: "#22C55E" },
      { name: "Declined", stageType: "cancelled", position: 5, color: "#EF4444" },
    ],
    defaultTags: ["Auto", "Home", "Life", "Commercial", "Renewal Due"],
    agentProfile: {
      focusArea: "Policy renewals, cross-sell opportunities, and lapsed clients",
      keyMetrics: ["Policies bound", "Renewal rate", "Premium volume"],
      avoidLanguage: ["deal", "close", "win rate"],
    },
  },

  real_estate: {
    id: "real_estate",
    label: "Real Estate",
    headline: "Transaction pipeline and client management",
    dailyFocus:
      "Track clients, showings, active transactions, and follow-up for real estate agents and brokerages.",
    labels: {
      customerSingular: "Client",
      customerPlural: "Clients",
      leadSingular: "Lead",
      leadPlural: "Leads",
      jobSingular: "Showing",
      jobPlural: "Showings",
      saleSingular: "Transaction",
      salePlural: "Transactions",
      followUpSingular: "Follow-up",
      followUpPlural: "Follow-ups",
    },
    priorityNames: {
      pipeline: "Transaction Pipeline",
      activeWork: "Active showings",
      revenue: "Transaction volume",
      followUps: "Follow-ups due",
      dataHealth: "Client data quality",
    },
    insightPrompts: [
      "Which leads haven't been contacted in over a week?",
      "Which transactions are under contract with upcoming closing dates?",
      "Which past clients haven't received a follow-up in over 90 days?",
    ],
    pipelineLabel: "Transaction Pipeline",
    recordLabel: "Transaction",
    recordPlural: "Transactions",
    completedLabel: "Closed",
    cancelledLabel: "Withdrawn",
    valueLabel: "Sale Price",
    invoiceLabel: "Commission Invoice",
    targetDateLabel: "Closing Date",
    activeStatusLabel: "Active",
    inactiveStatusLabel: "Inactive",
    closedStatusLabel: "Past Client",
    sourceOptions: ["Referral", "Zillow", "Realtor.com", "Open House", "Social Media", "Cold Call", "Repeat Client"],
    defaultBoardName: "Transaction Pipeline",
    defaultStages: [
      { name: "New Lead", stageType: "active", position: 1, color: "#6B7280" },
      { name: "Qualifying", stageType: "active", position: 2, color: "#3B82F6" },
      { name: "Active Search", stageType: "active", position: 3, color: "#8B5CF6" },
      { name: "Under Contract", stageType: "active", position: 4, color: "#F59E0B" },
      { name: "Closed", stageType: "completed", position: 5, color: "#22C55E" },
      { name: "Withdrawn", stageType: "cancelled", position: 6, color: "#EF4444" },
    ],
    defaultTags: ["Buyer", "Seller", "Investor", "First-time Buyer", "Relocation"],
    agentProfile: {
      focusArea: "Active searches, under-contract timelines, and referral follow-up",
      keyMetrics: ["Transactions closed", "Days on market", "Pipeline value"],
      avoidLanguage: ["opportunity", "deal stage", "win rate"],
    },
  },

  tattoo: {
    id: "tattoo",
    label: "Tattoo Studio",
    headline: "Booking board and project management",
    dailyFocus:
      "Track clients, consultations, deposits, sessions, and project completion for tattoo studios.",
    labels: {
      customerSingular: "Client",
      customerPlural: "Clients",
      leadSingular: "Inquiry",
      leadPlural: "Inquiries",
      jobSingular: "Session",
      jobPlural: "Sessions",
      saleSingular: "Payment",
      salePlural: "Payments",
      followUpSingular: "Follow-up",
      followUpPlural: "Follow-ups",
    },
    priorityNames: {
      pipeline: "Booking Board",
      activeWork: "Scheduled sessions",
      revenue: "Revenue",
      followUps: "Follow-ups due",
      dataHealth: "Client data quality",
    },
    insightPrompts: [
      "Which inquiries haven't been responded to in the past 48 hours?",
      "Which clients have paid a deposit but haven't scheduled their session?",
      "Which completed projects need a touch-up follow-up?",
    ],
    pipelineLabel: "Booking Board",
    recordLabel: "Project",
    recordPlural: "Projects",
    completedLabel: "Completed",
    cancelledLabel: "Cancelled",
    valueLabel: "Project Value",
    invoiceLabel: "Invoice",
    targetDateLabel: "Session Date",
    activeStatusLabel: "Active",
    inactiveStatusLabel: "Inactive",
    closedStatusLabel: "Closed",
    sourceOptions: ["Instagram", "Referral", "Walk-in", "Website", "TikTok", "Google"],
    defaultBoardName: "Booking Board",
    defaultStages: [
      { name: "Inquiry", stageType: "active", position: 1, color: "#6B7280" },
      { name: "Consultation", stageType: "active", position: 2, color: "#3B82F6" },
      { name: "Deposit Paid", stageType: "active", position: 3, color: "#8B5CF6" },
      { name: "Scheduled", stageType: "active", position: 4, color: "#F59E0B" },
      { name: "Completed", stageType: "completed", position: 5, color: "#22C55E" },
      { name: "Cancelled", stageType: "cancelled", position: 6, color: "#EF4444" },
    ],
    defaultTags: ["Large Project", "Touch-up Needed", "Regular Client", "Deposit Paid"],
    agentProfile: {
      focusArea: "Booking follow-up, deposit collection, and repeat client outreach",
      keyMetrics: ["Sessions booked", "Project completion rate", "Revenue per session"],
      avoidLanguage: ["sales pipeline", "deal", "win rate", "close"],
    },
  },

  auto_detailing: {
    id: "auto_detailing",
    label: "Auto Detailing",
    headline: "Service board and repeat customer tracking",
    dailyFocus:
      "Track customers, quote requests, scheduled details, and invoices for auto detailing businesses.",
    labels: {
      customerSingular: "Customer",
      customerPlural: "Customers",
      leadSingular: "Quote Request",
      leadPlural: "Quote Requests",
      jobSingular: "Detail",
      jobPlural: "Details",
      saleSingular: "Invoice",
      salePlural: "Invoices",
      followUpSingular: "Follow-up",
      followUpPlural: "Follow-ups",
    },
    priorityNames: {
      pipeline: "Service Board",
      activeWork: "Scheduled details",
      revenue: "Revenue",
      followUps: "Follow-ups due",
      dataHealth: "Customer data quality",
    },
    insightPrompts: [
      "Which customers haven't booked in the past 60 days?",
      "Which quote requests haven't received a response?",
      "Which invoices are outstanding or overdue?",
    ],
    pipelineLabel: "Service Board",
    recordLabel: "Service Package",
    recordPlural: "Service Packages",
    completedLabel: "Completed",
    cancelledLabel: "Cancelled",
    valueLabel: "Package Value",
    invoiceLabel: "Invoice",
    targetDateLabel: "Service Date",
    activeStatusLabel: "Active",
    inactiveStatusLabel: "Inactive",
    closedStatusLabel: "Closed",
    sourceOptions: ["Referral", "Instagram", "Google", "Website", "Repeat Customer", "Walk-in"],
    defaultBoardName: "Service Board",
    defaultStages: [
      { name: "Quote Requested", stageType: "active", position: 1, color: "#6B7280" },
      { name: "Quoted", stageType: "active", position: 2, color: "#3B82F6" },
      { name: "Scheduled", stageType: "active", position: 3, color: "#8B5CF6" },
      { name: "Completed", stageType: "completed", position: 4, color: "#22C55E" },
      { name: "Cancelled", stageType: "cancelled", position: 5, color: "#EF4444" },
    ],
    defaultTags: ["Fleet Account", "Ceramic Coating", "Interior Only", "Full Detail", "Repeat Customer"],
    agentProfile: {
      focusArea: "Repeat business, seasonal promotions, and referral follow-up",
      keyMetrics: ["Details completed", "Revenue per detail", "Repeat rate"],
      avoidLanguage: ["deal", "win rate", "close date", "pipeline"],
    },
  },
};

const parentSectorMap: Partial<Record<BusinessSector, BusinessSector>> = {
  dental: "medical",
  physical_therapy: "medical",
  mental_health: "medical",
  chiropractic: "medical",
  veterinary: "medical",
  general_contractor: "construction",
  electrical: "construction",
  plumbing: "construction",
  hvac: "construction",
  roofing: "construction",
  landscaping: "home_services",
  cleaning: "home_services",
  pest_control: "home_services",
  painting: "home_services",
  legal: "professional_services",
  accounting: "professional_services",
  consulting: "professional_services",
  agency: "professional_services",
  it_services: "professional_services",
  financial_advisory: "professional_services",
};

export function getParentSector(sector: BusinessSector): BusinessSector {
  return parentSectorMap[sector] ?? sector;
}

export function getAllProfiles(): IndustryProfile[] {
  return Object.values(industryProfiles);
}

export function getProfilesByGroup(): Array<{ group: string; profiles: IndustryProfile[] }> {
  const groups: Record<string, IndustryProfile[]> = {
    "General": [],
    "Medical & Healthcare": [],
    "Construction": [],
    "Home & Field Services": [],
    "Professional Services": [],
    "Other": [],
  };

  const groupMap: Partial<Record<BusinessSector, string>> = {
    general: "General",
    medical: "Medical & Healthcare",
    dental: "Medical & Healthcare",
    physical_therapy: "Medical & Healthcare",
    mental_health: "Medical & Healthcare",
    chiropractic: "Medical & Healthcare",
    veterinary: "Medical & Healthcare",
    construction: "Construction",
    general_contractor: "Construction",
    electrical: "Construction",
    plumbing: "Construction",
    hvac: "Construction",
    roofing: "Construction",
    home_services: "Home & Field Services",
    landscaping: "Home & Field Services",
    cleaning: "Home & Field Services",
    pest_control: "Home & Field Services",
    painting: "Home & Field Services",
    professional_services: "Professional Services",
    legal: "Professional Services",
    accounting: "Professional Services",
    consulting: "Professional Services",
    agency: "Professional Services",
    it_services: "Professional Services",
    financial_advisory: "Professional Services",
    fitness: "Other",
    photography: "Other",
    beauty: "Other",
    auto_repair: "Other",
  };

  for (const profile of Object.values(industryProfiles)) {
    const group = groupMap[profile.id] ?? "Other";
    groups[group].push(profile);
  }

  return Object.entries(groups)
    .filter(([, profiles]) => profiles.length > 0)
    .map(([group, profiles]) => ({ group, profiles }));
}

export const businessSectorOptions: Array<{
  group: string;
  options: Array<{ value: BusinessSector; label: string }>;
}> = getProfilesByGroup().map(({ group, profiles }) => ({
  group,
  options: profiles.map((p) => ({ value: p.id, label: p.label })),
}));

export const businessSectorOptionsFlat: Array<{ value: BusinessSector; label: string }> =
  Object.values(industryProfiles).map((p) => ({ value: p.id, label: p.label }));

const legacySectorAliases: Record<string, BusinessSector> = {
  dental_medical: "dental",
  field_service: "home_services",
  insurance: "financial_advisory",
  automotive: "auto_repair",
  retail: "general",
};

export function getIndustryProfile(
  businessSector?: string | null,
): IndustryProfile {
  if (!businessSector) {
    return industryProfiles.general;
  }

  if (businessSector in industryProfiles) {
    return industryProfiles[businessSector as BusinessSector];
  }

  const aliased = legacySectorAliases[businessSector];

  if (aliased) {
    return industryProfiles[aliased];
  }

  return industryProfiles.general;
}
